server.port=${PORT:8081}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:h2:mem:urldb}
spring.datasource.driver-class-name=${DB_DRIVER:org.h2.Driver}
spring.datasource.username=${DB_USER:sa}
spring.datasource.password=${DB_PASSWORD:}
spring.jpa.hibernate.ddl-auto=${DDL_AUTO:update}
spring.h2.console.enabled=true

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.cache.type=simple

spring.task.execution.pool.core-size=4

app.base-url=${APP_BASE_URL:http://localhost:8081}